language: php
php:
  - '5.5'
  - '5.6'
  - '7.0'
  - hhvm
  - nightly

services:
  - mysql

install:
  - composer self-update
  - composer install
  - npm install
  - gulp
  - php vendor/bin/codecept bootstrap
  - php artisan migrate

script:
  - php vendor/bin/codecept run

