language: php
php:
  - '5.5'
  - '5.6'
  - '7.0'
  - hhvm
  - nightly

matrix:
  allowed_failures:
    - php: hhvm
    - php: nightly

services:
  - mysql

install:
  - composer install
  - mysqladmin create -u root minimanager
  - php vendor/bin/codecept bootstrap
  - php artisan migrate

script:
  - php vendor/bin/codecept run

